### ISSUE TITLE
Templates y Layout

### ISSUE THREAD

**Issue by lucasjaviluna** [AlejoRetamal/TP-DdeS#5]
[High]
	He visto que en muchos componentes en el template hay duplicación en cuanto al uso de los componentes app-header, app-navbar y app-footer.
	Ej: https://vscode.dev/github/AlejoRetamal/TP-DdeS/blob/main/prototipos/Prosefy/src/app/pages/crear-cuenta/crear-cuenta.component.html#L1
	Esto es un error conceptual en aplicaciones SPA (single page applications). Lo que tendrían que hacer para aprovechar las capacidades de Angular y hacer más eficiente la aplicación
	y favorecer la legibilidad y mantenibilidad del código es: utilizar un layout (o template general) como el que vimos en clase. Ese layout va a tener una estructura base que es la que se va a repetir en la mayoría de las pantallas, es decir algo como:

``` 
<app-header></app-header>
	<app-navbar></app-navbar>
	<router-outlet></router-outlet>
	<app-footer></app-footer>```
	
De esta manera el template del layout va a tener la estructura básica de header, navbar y footer. Y en el centro un router-outlet que va a cargar el componente que corresponda según la ruta donde estoy parado actualmente

**Comment by AlejoRetamal** [comment]
Solucionado!
